### ISSUE TITLE
[MILESTONE] Make the project more accessible to future contributors and enhance governance

### ISSUE THREAD

**Issue by ehfd** [selkies-project/selkies-gstreamer#40]
These are the milestones before general availability. I can do some, some I need help.

- [x]  ~~Adequete documentation about setup on bare metal (not just containers), all the way from installing to startup.~~ Done.
- [x]  ~~An activate file that can be sourced to get the GStreamer environment up regardless of which path it is unpacked to~~ Done.
- [x] ~~How to add selkies-gstreamer in a container and also to optionally compile in a container.~~ Done.
- [x]  ~~Make the entrypoint or startup less cumbersome, a quick startup script maybe (with and without an option to start a new Xvfb and also the ability to set which DISPLAY)?~~ Documentation added.
- [x] ~~Include VP8 and VP9 encoding capabilities, although they currently only support software acceleration. The code is already there, but the vpx plugin is not included during GStreamer compilation.~~ Done.
- [x] ~~@danisla Find a way to integrate https://github.com/selkies-project/selkies-gstreamer/issues/6 to Selkies and not leave it to the user/OS or fix the issue altogether.~~ Fixed by #60.
- [x] ~~Check that all of the documentation instructions are valid and none fails.~~ Done.
- [x] ~~Governance event for MPLv2 license.~~ Pull request #62.
- [x] ~~Check fix for https://github.com/python-xlib/python-xlib/issues/233.~~ Fixed by #68.
- [x] ~~Address #43.~~ Patched by #73.
- [x] ~~GStreamer version upgrade. Depends on https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1605.~~ Upgraded to 1.22.5.
- [x] ~~Regardless, potentially convert docker-nvidia-egl-desktop and docker-nvidia-glx-desktop to selkies-project.~~ Done.
- [x] ~~Because of the warning message `rtpsession gstrtpsession.c:2435:gst_rtp_session_chain_send_rtp_common:<rtpsession0> Can't determine running time for this packet without knowing configured latency`, add a message handler after it does Gst.Pipeline.new(). Something that's going to regularly pop messages from the bus and process them, or a GLib mainloop and a bus signal handler like in that [helloworld example](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/main/subprojects/gst-python/examples/helloworld.py).~~
- [x] ~~Update outdated GitHub Actions pipeline.~~
- [x] ~~Pull Request and Issues Template.~~
- [x] ~~Fix existing CI processes, CI for building a documentation website; diet on README.md, clean/update the docs~~

Plans after the milestone:
-  ~~Manual compilation (all of gstreamer, web, py wheel) docs on bare metal on RHEL/SUSE, etc as well as Debian.~~ Nobody uses RHEL-based repositories regularly here, so we should wait for contributions from people who actually do.
- ~~Attempt a resolution to #7 (but not a critical issue). After the milestone.~~
- ~~Do #15. Try to preserve the single Dockerfile.example file, but use ARGS to install components in conditional. After the milestone.~~

**Comment by ehfd** [comment]
@danisla It is also a good idea to use the ~~Wiki~~Done and GitHub Sponsors.

**Comment by danisla** [comment]
I would like to see the documentation on a separate site and make the landing page README cleaner. Right now, when you visit this repo, it looks like a wall of text that scrolls on for many pages. It would be nice if the docs were in a format like [readthedocs](https://readthedocs.org/), or [Docsy](https://github.com/google/docsy-example).

I propose a separate documentation repository under the selkies-project org that I'll make you an admin of.

**Comment by ehfd** [comment]
> I would like to see the documentation on a separate site and make the landing page README cleaner. Right now, when you visit this repo, it looks like a wall of text that scrolls on for many pages. It would be nice if the docs were in a format like [readthedocs](https://readthedocs.org/), or [Docsy](https://github.com/google/docsy-example).

Yes, it was a makeshift solution, and it deserves a change.
But it could just be a docs directory instead of a new repository (and it's a MUST do for the journal) and build the static docs website from that directory. I would prefer a monorepo.
Or we could utilize the Wiki.

**Comment by ehfd** [comment]
@danisla Do you have any elegant solution in your style for #43?

**Comment by ehfd** [comment]
> I would like to see the documentation on a separate site and make the landing page README cleaner.

I think that we could activate GitHub pages for the https://selkies.io/gstreamer sub path or the subdomain https://gstreamer.selkies.io and build the documentation with GitHub Actions as a workflow in this repository. This is much cleaner than a separate docs repository. I like Docsy, we need to a static search functionality using [`lunr`](https://lunrjs.com) or some other method. I am against Algolia and other external search engines.

https://www.docsy.dev/docs/adding-content/navigation/#site-search-options

And for Sponsorship platforms:

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

Tidelift and Otechie: It's some paid service, I think. Out of the equation.

Patreon: Adequate for creators than developers. Takes commissions.

**Open Collective: For OSS projects. It can also be integrated with GitHub Sponsors or any other payment processing platform to go multi. It also provides auditing and fiscal management.**

Liberapay: Simple, that is good. But lacks features and no strong reason to choose over GitHub Sponsors.

Ko-fi: A no commission version of Patreon.

**IssueHunt: This is a great platform for individual developers. This is an alternative method for other people to crowdfund our issues for someone else to solve. This also frees us from fiscal management required in the Open Collective.**

**GitHub Sponsors: The default option for GitHub projects.**

LFX Mentorship (formerly CommunityBridge): Works only if we are affiliated with the Linux Foundation.

**Conclusion: I think IssueHunt is a great idea.**

**Comment by ehfd** [comment]
All are performed except documentation, which will be divided into multiple pages with enhanced readability and be updated.
